### ISSUE TITLE
Doesn't work when devDependencies are empty

### ISSUE THREAD

**Issue by AVGVSTVS96** [jherr/shadcn-differ#1]
Im experimenting with using this in Astro, I didn't list dev deps at first, so I got an error on line 27 of `create-diff.mjs` - `cannot convert undefined or null to object`. After adding dev deps, the error resolved.

Looks like this would happen to dependencies too, though it would be rare for dependencies to be empty.

**Comment by jherr** [comment]
Fixed and pushed as 1.0.3
